version: '3.3'
services:
  server:
    container_name: eop09-server:latest
    build:
      context: .
      dockerfile: server/cmd/server/Dockerfile
    volumes:
      - /tmp/app:/var/log/app
    ports:
      - "8081:8081"
    environment:
      - APP_ENV=local
      - APP_DSN=postgres://db/go_restful?sslmode=disable&user=postgres&password=postgres
    depends_on:
      db:
        condition: service_healthy
  mongo:
    image: "mongo:4.4.8"
    volumes: 
      - "~/mongo/eop90/db:/data/db"
      - "~/mongo/eop90/config:/data/config"
    command: --serviceExecutor adaptive --wiredTigerCacheSizeGB 1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Masa1818
